#!/usr/bin/env bash

if
  [[ -s "/home/vaishali/.rvm/gems/ruby-2.3.1/environment" ]]
then
  source "/home/vaishali/.rvm/gems/ruby-2.3.1/environment"
  exec tilt "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/vaishali/.rvm/gems/ruby-2.3.1/environment'" >&2
  exit 1
fi
