# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1485755260);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1485755380);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1485762100);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1485755140);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1485755020);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.blocked", "{\"4gPpjkxgZzXPVtuEoAL9Ig==\":1,\"IXSMHt58ocLbXl8Vw/g50Q==\":1}");
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150125221831");
user_pref("browser.slowStartup.averageTime", 2560);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150125221831");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1485758051288");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1485758966118");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1485758967945");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1485845367945");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1485757999176");
user_pref("datareporting.policy.firstRunTime", "1485329179378");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 594);
user_pref("datareporting.sessions.current.main", 31);
user_pref("datareporting.sessions.current.sessionRestored", 725);
user_pref("datareporting.sessions.current.startTime", "1485762320879");
user_pref("datareporting.sessions.current.totalTime", 26);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.5", "{\"s\":1485757983865,\"a\":98,\"t\":2097,\"c\":true,\"m\":731,\"fp\":4952,\"sr\":5257}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1485760186517,\"a\":146,\"t\":2133,\"c\":true,\"m\":421,\"fp\":1721,\"sr\":1816}");
user_pref("datareporting.sessions.prunedIndex", 4);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.07.01.beta,online-accounts%40lists.launchpad.net:0.5,ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1485755262);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"33.0\",\"st\":1485756581000,\"mt\":1422226951000}},\"app-system-share\":{\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1414004826000,\"mt\":1397665356000},\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"2.9\",\"st\":1485756643000,\"mt\":1420839876000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.07.01.beta\",\"st\":1414004824000,\"mt\":1404203370000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1414004826000,\"mt\":1390969548000}}}");
user_pref("gecko.buildID", "20150125221831");
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1485754843);
user_pref("loop.soft_start_ticket_number", 14103993);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1485329247);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1485754844);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1485758050);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1485493282);
user_pref("toolkit.startup.last_success", 1485762320);
user_pref("toolkit.telemetry.previousBuildID", "20150125221831");
